/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sign in
     * @description Any failure (unknown user, wrong password, locked or disabled account) answers the same `401`.
     */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List users */
    get: operations['listUsers']
    put?: never
    /** Create a user */
    post: operations['createUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a user */
    get: operations['getUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{userId}/roles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Assign a role
     * @description A reason is required. Assigning a role the user already has changes nothing.
     */
    post: operations['assignRole']
    /**
     * Revoke a role
     * @description The role and the reason travel in the request body. The last enabled administrator cannot lose
     *     the `PLATFORM_ADMIN` role (`409`, `USER_STATE_CONFLICT`).
     */
    delete: operations['revokeRole']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{userId}/enabled': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Enable or disable a user
     * @description A reason is required. The last enabled administrator cannot be disabled (`409`).
     */
    post: operations['setUserEnabled']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/organizations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List organizations */
    get: operations['listOrganizations']
    put?: never
    /** Create an organization */
    post: operations['createOrganization']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/organizations/{organizationId}/sites': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List the sites of an organization */
    get: operations['listSites']
    put?: never
    /** Create a site */
    post: operations['createSite']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/assets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List assets (cold units) */
    get: operations['listAssets']
    put?: never
    /** Register an asset */
    post: operations['registerAsset']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/assets/{assetId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get an asset */
    get: operations['getAsset']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update an asset
     * @description Partial update: a field that is absent or null stays as it is; a blank description clears it.
     *     `expectedVersion` must be the version you read; otherwise `409 CONCURRENT_MODIFICATION` (reload
     *     and retry). Sending nothing that changes writes nothing.
     */
    patch: operations['updateAsset']
    trace?: never
  }
  '/sensors': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List sensors */
    get: operations['listSensors']
    put?: never
    /**
     * Register a sensor
     * @description The sensor starts `ACTIVE` and is attached to the asset. The initial calibration and the
     *     operational profile are optional; a calibration needs a validity, from the profile given here
     *     or the service default, otherwise `409 CALIBRATION_VALIDITY_NOT_CONFIGURED`.
     */
    post: operations['registerSensor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sensors/connectivity': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Connectivity of the sensors
     * @description Connectivity is independent of the lifecycle status. Until this route exists, the Gateway
     *     resolves `connectivity` as a sensor id and answers `404`.
     */
    get: operations['listConnectivity']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sensors/{sensorId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a sensor */
    get: operations['getSensor']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update a sensor's technical data
     * @description Absent or null fields stay as they are. `expectedVersion` guards against a concurrent change.
     */
    patch: operations['updateSensor']
    trace?: never
  }
  '/sensors/{sensorId}/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the operational profile */
    get: operations['getProfile']
    /**
     * Create or replace the operational profile
     * @description `version` is the version you read (absent or 0 when creating). The service enforces the
     *     invariants (range, ordering of the magnitude bands, positive durations) and answers `400`.
     *     Sending an identical profile changes nothing.
     */
    put: operations['putProfile']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sensors/{sensorId}/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Change the sensor status
     * @description Allowed: any non-final status to `IN_MAINTENANCE`, `INACTIVE` or `RETIRED`. To `ACTIVE`: from
     *     `IN_MAINTENANCE` it needs a calibration recorded after entering maintenance
     *     (`CALIBRATION_EVIDENCE_REQUIRED`) that is still valid (`CALIBRATION_EXPIRED`); from `INACTIVE`
     *     it needs a calibration that has not expired. `RETIRED` is final. Anything else answers
     *     `409 SENSOR_TRANSITION_NOT_ALLOWED`.
     */
    post: operations['changeSensorStatus']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sensors/{sensorId}/calibrations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Record a calibration or verification
     * @description The expiry is derived (`performedAt` plus the profile's calibration validity, or the service
     *     default) and never supplied. Recording a calibration does **not** change the sensor status.
     */
    post: operations['recordCalibration']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sensors/{sensorId}/reassignment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Move the sensor to another asset
     * @description Only while `IN_MAINTENANCE`, to a different asset; the sensor stays in maintenance. The previous association is kept in the history.
     */
    post: operations['reassignSensor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sensors/{sensorId}/retirement': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Retire the sensor
     * @description Logical and final; nothing is deleted and the history stays readable.
     */
    post: operations['retireSensor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sensors/{sensorId}/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Administrative history of the sensor
     * @description Newest first. Every entry has who (`actorType` USER or SYSTEM, `actorId`), when, why and, when it
     *     applies, the value before and after. Automatic changes (calibration expiry) have `actorType`
     *     SYSTEM. Entries written by one operation share the same instant; their relative order is stable
     *     but has no chronological meaning.
     */
    get: operations['getSensorHistory']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sensors/{sensorId}/readings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Readings of a sensor
     * @description `from` and `to` are required; the server limits the range it serves.
     */
    get: operations['listReadings']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/telemetry/test-readings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Inject test readings
     * @description Goes through the same evaluation path as the simulator, so a reading outside the sensor's range
     *     creates an incident. Idempotent per `readingId`: resending a batch answers `DUPLICATE` and
     *     publishes nothing new. An invalid reading never aborts the others.
     */
    post: operations['injectTestReadings']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/incidents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List incidents */
    get: operations['listIncidents']
    put?: never
    /**
     * Create an incident (technical entry point)
     * @description **Legacy shape, do not integrate.** A technical entry point that exists only when the Gateway
     *     runs with `COLDGUARD_TECHNICAL_ENDPOINTS_ENABLED=true` (on in local Compose). Real incidents are
     *     created from telemetry. It will be replaced when SPEC-007 lands.
     */
    post: operations['createIncident']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/incidents/{incidentId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get an incident */
    get: operations['getIncident']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/incidents/{incidentId}/acknowledgement': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Acknowledge an incident
     * @description Moves `CREATED` to `ACKNOWLEDGED`. A second acknowledgement answers `409 INCIDENT_ALREADY_ACKNOWLEDGED`.
     */
    post: operations['acknowledgeIncident']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/incidents/{incidentId}/escalation': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Escalate an incident
     * @description A reason is required.
     */
    post: operations['escalateIncident']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/incidents/{incidentId}/close': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Close an incident
     * @description Only the maintenance technician closes an incident. **Legacy response shape, do not integrate
     *     yet:** today it answers `LegacyCloseIncidentResponse`; with SPEC-007 it answers the full
     *     `Incident` (with `cause`, `resolutionComment`, `closedAt`, `closedBy` persisted).
     */
    post: operations['closeIncident']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/metrics/incidents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Operational metrics of incidents
     * @description `from` and `to` bound the incident creation time and are required.
     */
    get: operations['getIncidentMetrics']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/audit-records': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Audit log
     * @description Read-only. `from` and `to` are required; the server limits the range.
     */
    get: operations['listAuditRecords']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ProblemDetail: {
      /** @example about:blank */
      type?: string
      /** @example Conflict */
      title: string
      /** @example 409 */
      status: number
      detail?: string
      /** @description Path of the request. */
      instance?: string
      /**
       * @description Stable machine-readable code; branch on this, not on `detail`.
       * @example SENSOR_TRANSITION_NOT_ALLOWED
       */
      code: string
      correlationId?: string
      /** @description Present on `INVALID_REQUEST`; one entry per invalid field. */
      errors?: {
        /** @example reason */
        field: string
        /** @example must not be blank */
        message: string
      }[]
    }
    PageInfo: {
      page: number
      size: number
      /** Format: int64 */
      totalElements: number
      totalPages: number
    }
    /** @enum {string} */
    Role:
      'OPERATIONS_SUPERVISOR' | 'OPERATOR' | 'MAINTENANCE_TECHNICIAN' | 'AUDITOR' | 'PLATFORM_ADMIN'
    /** @enum {string} */
    Criticality: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
    /** @enum {string} */
    SensorStatus: 'ACTIVE' | 'IN_MAINTENANCE' | 'INACTIVE' | 'RETIRED'
    /** @enum {string} */
    CalibrationKind: 'CALIBRATION' | 'VERIFICATION'
    LoginRequest: {
      username: string
      /** Format: password */
      password: string
    }
    LoginResponse: {
      accessToken: string
      /** @example Bearer */
      tokenType: string
      /**
       * Format: int64
       * @description Seconds until it expires.
       */
      expiresIn: number
    }
    User: {
      userId: string
      username: string
      email: string
      displayName: string
      roles: components['schemas']['Role'][]
      enabled: boolean
      /** Format: date-time */
      createdAt: string
    }
    UserPage: {
      items: components['schemas']['User'][]
      page: components['schemas']['PageInfo']
    }
    CreateUserRequest: {
      username: string
      email: string
      displayName: string
      /** Format: password */
      initialPassword: string
      roles: components['schemas']['Role'][]
    }
    RoleChangeRequest: {
      role: components['schemas']['Role']
      reason: string
    }
    EnabledRequest: {
      enabled: boolean
      reason: string
    }
    Organization: {
      id: string
      name: string
      /** Format: date-time */
      createdAt: string
    }
    OrganizationPage: {
      items: components['schemas']['Organization'][]
      page: components['schemas']['PageInfo']
    }
    CreateOrganizationRequest: {
      name: string
    }
    Site: {
      id: string
      organizationId: string
      name: string
      address?: string | null
      /** Format: date-time */
      createdAt: string
    }
    SitePage: {
      items: components['schemas']['Site'][]
      page: components['schemas']['PageInfo']
    }
    CreateSiteRequest: {
      name: string
      address?: string
    }
    Asset: {
      id: string
      siteId: string
      name: string
      description?: string | null
      criticality: components['schemas']['Criticality']
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
      /**
       * Format: int64
       * @description Send it back as `expectedVersion` when updating.
       */
      version: number
    }
    AssetPage: {
      items: components['schemas']['Asset'][]
      page: components['schemas']['PageInfo']
    }
    RegisterAssetRequest: {
      siteId: string
      name: string
      description?: string
      criticality: components['schemas']['Criticality']
    }
    UpdateAssetRequest: {
      /** Format: int64 */
      expectedVersion: number
      name?: string
      description?: string
      criticality?: components['schemas']['Criticality']
    }
    Sensor: {
      id: string
      serialNumber: string
      model?: string | null
      /** @example CELSIUS */
      measurementUnit: string
      assetId: string
      status: components['schemas']['SensorStatus']
      /** Format: date-time */
      statusChangedAt: string
      /** Format: date-time */
      lastCalibrationRecordedAt?: string | null
      /** Format: date-time */
      lastCalibrationValidUntil?: string | null
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
      /** Format: int64 */
      version: number
    }
    SensorPage: {
      items: components['schemas']['Sensor'][]
      page: components['schemas']['PageInfo']
    }
    InitialCalibration: {
      kind: components['schemas']['CalibrationKind']
      /** Format: date-time */
      performedAt: string
      reason: string
    }
    RegisterSensorRequest: {
      assetId: string
      serialNumber: string
      model?: string
      /** @example CELSIUS */
      measurementUnit: string
      initialCalibration?: components['schemas']['InitialCalibration']
      profile?: components['schemas']['OperationalProfileRequest']
    }
    UpdateSensorRequest: {
      /** Format: int64 */
      expectedVersion: number
      serialNumber?: string
      model?: string
    }
    /** @description Deviation, in the profile's unit, from which an anomaly reaches each magnitude (0 < medium < high < critical). */
    MagnitudeBands: {
      /** Format: double */
      mediumFrom: number
      /** Format: double */
      highFrom: number
      /** Format: double */
      criticalFrom: number
    }
    /** @description An anomaly is persistent after this many consecutive out-of-range readings within the window. */
    Persistence: {
      minConsecutiveBreaches: number
      windowSeconds: number
    }
    OperationalProfileRequest: {
      /** Format: double */
      minTemperature: number
      /** Format: double */
      maxTemperature: number
      /** @description Must match the sensor's measurement unit. */
      unit: string
      magnitudeBands: components['schemas']['MagnitudeBands']
      persistence: components['schemas']['Persistence']
      expectedReadingIntervalSeconds: number
      /**
       * Format: int64
       * @description When absent
       */
      calibrationValiditySeconds?: number | null
      /**
       * Format: int64
       * @description The version you read; absent or 0 when creating.
       */
      version?: number
    }
    OperationalProfile: {
      sensorId: string
      /** Format: double */
      minTemperature: number
      /** Format: double */
      maxTemperature: number
      unit: string
      magnitudeBands: components['schemas']['MagnitudeBands']
      persistence: components['schemas']['Persistence']
      expectedReadingIntervalSeconds: number
      /** Format: int64 */
      calibrationValiditySeconds?: number | null
      /**
       * Format: int64
       * @description Starts at 1; send it back as `version` when replacing.
       */
      version: number
      /** Format: date-time */
      updatedAt: string
    }
    StatusChangeRequest: {
      targetStatus: components['schemas']['SensorStatus']
      reason: string
    }
    CalibrationRequest: {
      kind: components['schemas']['CalibrationKind']
      /**
       * Format: date-time
       * @description Must not be in the future.
       */
      performedAt: string
      reason: string
    }
    Calibration: {
      id: string
      sensorId: string
      kind: components['schemas']['CalibrationKind']
      /** Format: date-time */
      performedAt: string
      /** Format: date-time */
      validUntil: string
      /** Format: date-time */
      recordedAt: string
      recordedBy: string
      reason: string
    }
    ReassignmentRequest: {
      targetAssetId: string
      reason: string
    }
    RetirementRequest: {
      reason: string
    }
    HistoryEntry: {
      id: string
      /**
       * @description The kind of change.
       * @enum {string}
       */
      action:
        | 'REGISTERED'
        | 'TECHNICAL_DATA_UPDATED'
        | 'PROFILE_UPDATED'
        | 'STATUS_CHANGED'
        | 'CALIBRATION_RECORDED'
        | 'REASSIGNED'
        | 'RETIRED'
      previousValue?: {
        [key: string]: unknown
      } | null
      newValue?: {
        [key: string]: unknown
      } | null
      reason?: string | null
      /** @enum {string} */
      actorType: 'USER' | 'SYSTEM'
      /** @description A user id */
      actorId: string
      /** Format: date-time */
      occurredAt: string
    }
    HistoryPage: {
      items: components['schemas']['HistoryEntry'][]
      /** @description Empty on the last page. */
      nextCursor: string
      hasMore: boolean
    }
    /** @enum {string} */
    ReadingSource: 'SIMULATOR' | 'TEST_INJECTION'
    /** @enum {string} */
    MagnitudeLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
    Reading: {
      /** @description UUID generated by the producer; makes ingestion idempotent. */
      readingId: string
      sensorId: string
      /** Format: date-time */
      recordedAt: string
      /** Format: double */
      value: number
      unit: string
    }
    TestReadingsRequest: {
      readings: components['schemas']['Reading'][]
    }
    ReadingResult: {
      readingId: string
      /** @enum {string} */
      outcome: 'ACCEPTED' | 'DUPLICATE' | 'REJECTED'
      /** @description False when the sensor is not ACTIVE or has no profile. */
      eligible?: boolean
      /** @description True when the reading is an anomaly. */
      breached?: boolean
      /** @example UNIT_MISMATCH */
      rejectionCode?: string | null
    }
    TestReadingsResponse: {
      results: components['schemas']['ReadingResult'][]
    }
    ReadingView: {
      readingId: string
      sensorId: string
      assetId: string
      /** Format: date-time */
      recordedAt: string
      /** Format: date-time */
      receivedAt: string
      /** Format: double */
      value: number
      unit: string
      source: components['schemas']['ReadingSource']
      eligible: boolean
      /** @enum {string|null} */
      ineligibilityReason?: 'SENSOR_NOT_ACTIVE' | 'NO_PROFILE' | null
      breached: boolean
      anomalyType?: string | null
      magnitude?: components['schemas']['MagnitudeLevel']
    }
    ReadingPage: {
      items: components['schemas']['ReadingView'][]
      nextCursor: string
      hasMore: boolean
    }
    Connectivity: {
      sensorId: string
      assetId: string
      /** Format: date-time */
      lastReadingAt?: string | null
      expectedReadingIntervalSeconds: number
      /**
       * Format: date-time
       * @description Absent while connected.
       */
      connectivityLostAt?: string | null
    }
    ConnectivityPage: {
      items: components['schemas']['Connectivity'][]
      page: components['schemas']['PageInfo']
    }
    /** @enum {string} */
    IncidentStatus: 'CREATED' | 'ACKNOWLEDGED' | 'ESCALATED' | 'CLOSED'
    /** @enum {string} */
    Priority: 'P1' | 'P2' | 'P3' | 'P4'
    /** @enum {string} */
    Impact: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
    /** @enum {string} */
    Urgency: 'LOW' | 'MEDIUM' | 'HIGH' | 'IMMEDIATE'
    Incident: {
      id: string
      status: components['schemas']['IncidentStatus']
      assetId: string
      sensorId: string
      /** @example HIGH_TEMPERATURE */
      anomalyType: string
      impact: components['schemas']['Impact']
      urgency: components['schemas']['Urgency']
      priority: components['schemas']['Priority']
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      ackDueAt?: string | null
      /**
       * Format: date-time
       * @description Absent when the priority has no resolution target.
       */
      resolveDueAt?: string | null
      /** Format: date-time */
      acknowledgedAt?: string | null
      acknowledgedBy?: string | null
      /** Format: date-time */
      lastEscalatedAt?: string | null
      escalationCount: number
      /** Format: date-time */
      closedAt?: string | null
      closedBy?: string | null
      cause?: string | null
      resolutionComment?: string | null
      /** @description Equivalent anomalies seen while the incident is open. */
      occurrenceCount: number
      /** Format: date-time */
      lastOccurrenceAt?: string | null
    }
    IncidentPage: {
      items: components['schemas']['Incident'][]
      page: components['schemas']['PageInfo']
    }
    AcknowledgementRequest: {
      note?: string
    }
    EscalationRequest: {
      reason: string
    }
    CloseIncidentRequest: {
      cause: string
      resolutionComment: string
    }
    /** @description Protocol-prefixed vocabulary; do not integrate. Replaced by SPEC-007. */
    LegacyCreateIncidentRequest: {
      assetId?: string
      /** @enum {string} */
      assetCriticality?:
        'CRITICALITY_LOW' | 'CRITICALITY_MEDIUM' | 'CRITICALITY_HIGH' | 'CRITICALITY_CRITICAL'
      sensorId?: string
      anomalyType?: string
      /** @enum {string} */
      magnitude?: 'MAGNITUDE_LOW' | 'MAGNITUDE_MEDIUM' | 'MAGNITUDE_HIGH' | 'MAGNITUDE_CRITICAL'
      persistent?: boolean
      correlationId?: string
    }
    /** @description Protocol-prefixed vocabulary; do not integrate. Replaced by SPEC-007. */
    LegacyCreateIncidentResponse: {
      incidentId?: string
      status?: string
      /** @example IMPACT_HIGH */
      impact?: string
      /** @example URGENCY_IMMEDIATE */
      urgency?: string
      /** @example P1 */
      priority?: string
      createdAt?: string
    }
    /** @description Replaced by the full `Incident` in SPEC-007; do not integrate. */
    LegacyCloseIncidentResponse: {
      incidentId?: string
      /** @example CLOSED */
      status?: string
      closedAt?: string
    }
    IncidentMetrics: {
      /** @description Keys are incident statuses. */
      countByStatus: {
        [key: string]: number
      }
      /** @description Keys are P1 to P4. */
      countByPriority: {
        [key: string]: number
      }
      /**
       * Format: double
       * @description Mean time to acknowledge; absent when none was acknowledged.
       */
      mttaSeconds?: number | null
      /**
       * Format: double
       * @description Mean time to resolve; absent when none was closed.
       */
      mttrSeconds?: number | null
      byPriority: components['schemas']['PriorityMetrics'][]
    }
    PriorityMetrics: {
      priority: components['schemas']['Priority']
      /** Format: int64 */
      total: number
      /** Format: int64 */
      acknowledged: number
      /** Format: int64 */
      acknowledgedOnTime: number
      /** Format: int64 */
      closed: number
      /** Format: int64 */
      closedOnTime: number
      /**
       * Format: double
       * @description Absent when nothing is evaluable.
       */
      ackComplianceRatio?: number | null
      /** Format: double */
      resolveComplianceRatio?: number | null
    }
    AuditRecord: {
      id: string
      /** Format: date-time */
      occurredAt: string
      /** @example incident-service */
      sourceService: string
      /** @example Incident */
      entityType: string
      entityId: string
      action: string
      /** @enum {string} */
      actorType: 'USER' | 'SYSTEM'
      actorId: string
      reason?: string | null
      previousValue?: {
        [key: string]: unknown
      } | null
      newValue?: {
        [key: string]: unknown
      } | null
      correlationId?: string | null
    }
    AuditRecordPage: {
      items: components['schemas']['AuditRecord'][]
      nextCursor: string
      hasMore: boolean
    }
  }
  responses: {
    /**
     * @description The request is not valid. `code` is `INVALID_REQUEST` (with `errors` naming each invalid field,
     *     never its value), `MALFORMED_REQUEST_BODY`, or a business code of the service.
     */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
    /** @description No valid token, or `INVALID_CREDENTIALS` on login. Sign in again. */
    Unauthorized: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
    /** @description The token is valid but its roles do not allow this operation. */
    Forbidden: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
    /**
     * @description The resource does not exist (an id that is not valid cannot exist either). `code` names it:
     *     `ASSET_NOT_FOUND`, `SITE_NOT_FOUND`, `SENSOR_NOT_FOUND`, `ORGANIZATION_NOT_FOUND`,
     *     `PROFILE_NOT_FOUND`, `USER_NOT_FOUND`, `INCIDENT_NOT_FOUND`.
     */
    NotFound: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
    /**
     * @description The state does not allow it, or the data clashes. `CONCURRENT_MODIFICATION` means someone else
     *     changed the resource: reload it and retry. Others: `SENSOR_SERIAL_DUPLICATED`,
     *     `ORGANIZATION_NAME_DUPLICATED`, `SITE_NAME_DUPLICATED`, `USER_ALREADY_EXISTS`,
     *     `USER_STATE_CONFLICT`, `SENSOR_TRANSITION_NOT_ALLOWED`, `CALIBRATION_EVIDENCE_REQUIRED`,
     *     `CALIBRATION_EXPIRED`, `CALIBRATION_VALIDITY_NOT_CONFIGURED`, `REASSIGNMENT_NOT_ALLOWED`,
     *     `INCIDENT_ALREADY_EXISTS`, `INCIDENT_ALREADY_ACKNOWLEDGED`, `INCIDENT_ALREADY_CLOSED`.
     */
    Conflict: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
    /**
     * @description A downstream service failed: `UPSTREAM_ERROR` (502), `UPSTREAM_UNAVAILABLE` (503) or
     *     `UPSTREAM_TIMEOUT` (504). The internal cause is never exposed; the `correlationId` identifies it
     *     in the logs.
     */
    BadGateway: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
  }
  parameters: {
    /** @description Zero-based page number. */
    Page: number
    /** @description Page size; 0 or omitted selects the server default (20); the maximum is 100. */
    Size: number
    /** @description Opaque cursor taken from `nextCursor`; omit it for the first page. */
    Cursor: string
    UserId: string
    OrganizationId: string
    AssetId: string
    SensorId: string
    IncidentId: string
  }
  requestBodies: never
  headers: {
    /** @description URL of the created resource */
    Location: string
  }
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Signed in */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponse']
        }
      }
      401: components['responses']['Unauthorized']
      502: components['responses']['BadGateway']
    }
  }
  listUsers: {
    parameters: {
      query?: {
        /** @description Zero-based page number. */
        page?: components['parameters']['Page']
        /** @description Page size; 0 or omitted selects the server default (20); the maximum is 100. */
        size?: components['parameters']['Size']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of users */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserPage']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  createUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      409: components['responses']['Conflict']
    }
  }
  getUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        userId: components['parameters']['UserId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  assignRole: {
    parameters: {
      query?: never
      header?: never
      path: {
        userId: components['parameters']['UserId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RoleChangeRequest']
      }
    }
    responses: {
      /** @description The updated user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  revokeRole: {
    parameters: {
      query?: never
      header?: never
      path: {
        userId: components['parameters']['UserId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RoleChangeRequest']
      }
    }
    responses: {
      /** @description The updated user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  setUserEnabled: {
    parameters: {
      query?: never
      header?: never
      path: {
        userId: components['parameters']['UserId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EnabledRequest']
      }
    }
    responses: {
      /** @description The updated user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  listOrganizations: {
    parameters: {
      query?: {
        /** @description Zero-based page number. */
        page?: components['parameters']['Page']
        /** @description Page size; 0 or omitted selects the server default (20); the maximum is 100. */
        size?: components['parameters']['Size']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of organizations */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OrganizationPage']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  createOrganization: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateOrganizationRequest']
      }
    }
    responses: {
      /** @description Created (organizations cannot be fetched by id, so there is no `Location`) */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Organization']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      409: components['responses']['Conflict']
    }
  }
  listSites: {
    parameters: {
      query?: {
        /** @description Zero-based page number. */
        page?: components['parameters']['Page']
        /** @description Page size; 0 or omitted selects the server default (20); the maximum is 100. */
        size?: components['parameters']['Size']
      }
      header?: never
      path: {
        organizationId: components['parameters']['OrganizationId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of sites */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SitePage']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  createSite: {
    parameters: {
      query?: never
      header?: never
      path: {
        organizationId: components['parameters']['OrganizationId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSiteRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Site']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  listAssets: {
    parameters: {
      query?: {
        siteId?: string
        /** @description Zero-based page number. */
        page?: components['parameters']['Page']
        /** @description Page size; 0 or omitted selects the server default (20); the maximum is 100. */
        size?: components['parameters']['Size']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of assets */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AssetPage']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  registerAsset: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterAssetRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          Location: components['headers']['Location']
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Asset']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  getAsset: {
    parameters: {
      query?: never
      header?: never
      path: {
        assetId: components['parameters']['AssetId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The asset */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Asset']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  updateAsset: {
    parameters: {
      query?: never
      header?: never
      path: {
        assetId: components['parameters']['AssetId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAssetRequest']
      }
    }
    responses: {
      /** @description The updated asset */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Asset']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  listSensors: {
    parameters: {
      query?: {
        assetId?: string
        status?: components['schemas']['SensorStatus']
        /** @description Zero-based page number. */
        page?: components['parameters']['Page']
        /** @description Page size; 0 or omitted selects the server default (20); the maximum is 100. */
        size?: components['parameters']['Size']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of sensors */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SensorPage']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  registerSensor: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterSensorRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          Location: components['headers']['Location']
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Sensor']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  listConnectivity: {
    parameters: {
      query?: {
        onlyLost?: boolean
        /** @description Zero-based page number. */
        page?: components['parameters']['Page']
        /** @description Page size; 0 or omitted selects the server default (20); the maximum is 100. */
        size?: components['parameters']['Size']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of connectivity statuses */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConnectivityPage']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getSensor: {
    parameters: {
      query?: never
      header?: never
      path: {
        sensorId: components['parameters']['SensorId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The sensor */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Sensor']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  updateSensor: {
    parameters: {
      query?: never
      header?: never
      path: {
        sensorId: components['parameters']['SensorId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSensorRequest']
      }
    }
    responses: {
      /** @description The updated sensor */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Sensor']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  getProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        sensorId: components['parameters']['SensorId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The profile */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OperationalProfile']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  putProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        sensorId: components['parameters']['SensorId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OperationalProfileRequest']
      }
    }
    responses: {
      /** @description The stored profile */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OperationalProfile']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  changeSensorStatus: {
    parameters: {
      query?: never
      header?: never
      path: {
        sensorId: components['parameters']['SensorId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StatusChangeRequest']
      }
    }
    responses: {
      /** @description The updated sensor */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Sensor']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  recordCalibration: {
    parameters: {
      query?: never
      header?: never
      path: {
        sensorId: components['parameters']['SensorId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CalibrationRequest']
      }
    }
    responses: {
      /** @description Recorded (calibrations are not fetched by id, so there is no `Location`) */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Calibration']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  reassignSensor: {
    parameters: {
      query?: never
      header?: never
      path: {
        sensorId: components['parameters']['SensorId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReassignmentRequest']
      }
    }
    responses: {
      /** @description The updated sensor */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Sensor']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  retireSensor: {
    parameters: {
      query?: never
      header?: never
      path: {
        sensorId: components['parameters']['SensorId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RetirementRequest']
      }
    }
    responses: {
      /** @description The retired sensor */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Sensor']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  getSensorHistory: {
    parameters: {
      query?: {
        /** @description Opaque cursor taken from `nextCursor`; omit it for the first page. */
        cursor?: components['parameters']['Cursor']
        /** @description Page size; 0 or omitted selects the server default (20); the maximum is 100. */
        size?: components['parameters']['Size']
      }
      header?: never
      path: {
        sensorId: components['parameters']['SensorId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of history entries */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HistoryPage']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  listReadings: {
    parameters: {
      query: {
        from: string
        to: string
        /** @description Opaque cursor taken from `nextCursor`; omit it for the first page. */
        cursor?: components['parameters']['Cursor']
        /** @description Page size; 0 or omitted selects the server default (20); the maximum is 100. */
        size?: components['parameters']['Size']
      }
      header?: never
      path: {
        sensorId: components['parameters']['SensorId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of readings */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReadingPage']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  injectTestReadings: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TestReadingsRequest']
      }
    }
    responses: {
      /** @description One result per reading, in input order */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TestReadingsResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  listIncidents: {
    parameters: {
      query?: {
        /** @description Repeat to filter by several statuses. */
        status?: components['schemas']['IncidentStatus'][]
        /** @description Repeat to filter by several priorities. */
        priority?: components['schemas']['Priority'][]
        assetId?: string
        sensorId?: string
        createdFrom?: string
        createdTo?: string
        /** @description Zero-based page number. */
        page?: components['parameters']['Page']
        /** @description Page size; 0 or omitted selects the server default (20); the maximum is 100. */
        size?: components['parameters']['Size']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of incidents */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IncidentPage']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  createIncident: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LegacyCreateIncidentRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LegacyCreateIncidentResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      409: components['responses']['Conflict']
    }
  }
  getIncident: {
    parameters: {
      query?: never
      header?: never
      path: {
        incidentId: components['parameters']['IncidentId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The incident */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Incident']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  acknowledgeIncident: {
    parameters: {
      query?: never
      header?: never
      path: {
        incidentId: components['parameters']['IncidentId']
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['AcknowledgementRequest']
      }
    }
    responses: {
      /** @description The updated incident */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Incident']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  escalateIncident: {
    parameters: {
      query?: never
      header?: never
      path: {
        incidentId: components['parameters']['IncidentId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EscalationRequest']
      }
    }
    responses: {
      /** @description The updated incident */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Incident']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  closeIncident: {
    parameters: {
      query?: never
      header?: never
      path: {
        incidentId: components['parameters']['IncidentId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CloseIncidentRequest']
      }
    }
    responses: {
      /** @description Closed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LegacyCloseIncidentResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  getIncidentMetrics: {
    parameters: {
      query: {
        from: string
        to: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The metrics */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IncidentMetrics']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  listAuditRecords: {
    parameters: {
      query: {
        entityType?: string
        entityId?: string
        actorId?: string
        action?: string
        from: string
        to: string
        /** @description Opaque cursor taken from `nextCursor`; omit it for the first page. */
        cursor?: components['parameters']['Cursor']
        /** @description Page size; 0 or omitted selects the server default (20); the maximum is 100. */
        size?: components['parameters']['Size']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of audit records */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuditRecordPage']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
}
